# Site settings
title: Jim's Technical Blog
email: jim_xu@outlook.com
description: This is Jim's technical blog.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "xujim.github.io"
twitter_username: xujian1030
github_username:  xujim

# Build settings
markdown: kramdown
